name: wanandroid
description: WanAndroid Flutter.
publish_to: 'none' 
version: 1.0.4+5

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  uuid: ^3.0.5
  url_launcher: ^6.0.17
  equatable: ^2.0.3
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  path_provider: ^2.0.8
  shared_preferences: ^2.0.11
  flutter_swiper_null_safety: ^1.0.2
  json_annotation: ^4.4.0
  flutter_inappwebview: ^5.3.2
  percent_indicator: ^3.4.0
  event_bus: ^2.0.0
  flutter_html: ^3.0.0-alpha.1
  flutter_staggered_grid_view: ^0.6.0
  cached_network_image: ^3.2.0
  flutter_swipe_action_cell: ^2.1.5
  qr_code_scanner: ^0.6.1
  permission_handler: ^8.3.0
  ota_update: ^4.0.1
  package_info_plus: ^1.3.0
  share_plus: ^3.0.4
  qr_flutter: ^4.0.0
  share_files_and_screenshot_widgets_plus: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.3
  build_runner: ^2.1.7 # run cmd on termial: flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/images/logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: Strings # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/env/l10n/arb # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/env/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: true # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
